// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TesteDesenvolvedor.Repository.Context;

namespace TesteDesenvolvedor.Repository.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("TesteDesenvolvedor.Domain.Linha", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Linhas");
                });

            modelBuilder.Entity("TesteDesenvolvedor.Domain.LinhaParada", b =>
                {
                    b.Property<long>("LinhaId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParadaId")
                        .HasColumnType("bigint");

                    b.HasKey("LinhaId", "ParadaId");

                    b.HasIndex("ParadaId");

                    b.ToTable("LinhasParadas");
                });

            modelBuilder.Entity("TesteDesenvolvedor.Domain.Parada", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Paradas");
                });

            modelBuilder.Entity("TesteDesenvolvedor.Domain.PosicaoVeiculo", b =>
                {
                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<long>("VeiculoId")
                        .HasColumnType("bigint");

                    b.HasIndex("VeiculoId");

                    b.ToTable("PosicaoVeiculos");
                });

            modelBuilder.Entity("TesteDesenvolvedor.Domain.Veiculo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<long>("LinhaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Modelo")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LinhaId");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("TesteDesenvolvedor.Domain.LinhaParada", b =>
                {
                    b.HasOne("TesteDesenvolvedor.Domain.Linha", "Linha")
                        .WithMany("LinhasParadas")
                        .HasForeignKey("LinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesteDesenvolvedor.Domain.Parada", "Parada")
                        .WithMany("LinhaParadas")
                        .HasForeignKey("ParadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linha");

                    b.Navigation("Parada");
                });

            modelBuilder.Entity("TesteDesenvolvedor.Domain.PosicaoVeiculo", b =>
                {
                    b.HasOne("TesteDesenvolvedor.Domain.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("TesteDesenvolvedor.Domain.Veiculo", b =>
                {
                    b.HasOne("TesteDesenvolvedor.Domain.Linha", "Linha")
                        .WithMany("Veiculos")
                        .HasForeignKey("LinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linha");
                });

            modelBuilder.Entity("TesteDesenvolvedor.Domain.Linha", b =>
                {
                    b.Navigation("LinhasParadas");

                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("TesteDesenvolvedor.Domain.Parada", b =>
                {
                    b.Navigation("LinhaParadas");
                });
#pragma warning restore 612, 618
        }
    }
}
