// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TesteDesenvolvedor.Repository.Context;

namespace TesteDesenvolvedor.Repository.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("TesteDesenvolvedor.Domain.Linha", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("ParadaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Linhas");
                });

            modelBuilder.Entity("TesteDesenvolvedor.Domain.Parada", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<long?>("LinhaId")
                        .HasColumnType("bigint");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LinhaId");

                    b.ToTable("Paradas");
                });

            modelBuilder.Entity("TesteDesenvolvedor.Domain.PosicaoVeiculo", b =>
                {
                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double>("VeiculoId")
                        .HasColumnType("double precision");

                    b.Property<long?>("VeiculoId1")
                        .HasColumnType("bigint");

                    b.HasIndex("VeiculoId1");

                    b.ToTable("PosicaoVeiculos");
                });

            modelBuilder.Entity("TesteDesenvolvedor.Domain.Veiculo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("LinhaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Modelo")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LinhaId");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("TesteDesenvolvedor.Domain.Parada", b =>
                {
                    b.HasOne("TesteDesenvolvedor.Domain.Linha", null)
                        .WithMany("Paradas")
                        .HasForeignKey("LinhaId");
                });

            modelBuilder.Entity("TesteDesenvolvedor.Domain.PosicaoVeiculo", b =>
                {
                    b.HasOne("TesteDesenvolvedor.Domain.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId1");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("TesteDesenvolvedor.Domain.Veiculo", b =>
                {
                    b.HasOne("TesteDesenvolvedor.Domain.Linha", "Linha")
                        .WithMany()
                        .HasForeignKey("LinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linha");
                });

            modelBuilder.Entity("TesteDesenvolvedor.Domain.Linha", b =>
                {
                    b.Navigation("Paradas");
                });
#pragma warning restore 612, 618
        }
    }
}
